# Setup
title:       MoeGirls.moe Offical Blog 
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Yanghua Jin
  url:        http://makegirlsmoe.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
